
jobqueue:

  juwels-jobqueue-config:

    ### Dask jobqueue worker options ###

    cores: 96
    memory: 86864MiB

    processes: 1

    local-directory: null
    death-timeout: 60

    extra: []
    interface: ib0

    ### SLURM job script options ####

    shebang: '#!/usr/bin/env bash'
    walltime: '00:15:00'
    log-directory: dask-jobqueue-logs
    name: dask-worker
    
    # https://docs.dask.org/en/latest/setup/hpc.html

    env-extra: ['export DASK_DISTRIBUTED__WORKER__MEMORY__SPILL=False',
                'export DASK_DISTRIBUTED__WORKER__MEMORY__TARGET=False',
                'export DASK_DISTRIBUTED__WORKER__MEMORY__PAUSE=0.8',
                'export DASK_DISTRIBUTED__WORKER__MEMORY__TERMINATE=0.9']

    # these depend on project affiliation
    # and ready-to-use compute resources, and
    # therefore should be set manually
    
    project: null
    queue: null

    # for SLURM clusters these are automatically set
    # by the Dask worker options above
    
    job-cpu: null
    job-mem: null

    # these are stated here because they are mandatory for
    # Dask jobqueue standalone configurations
    
    job-extra: []
